AB#705 Refactor quickstart
edgelesssys/marblerun.sh pull request #23
Opened 2021-03-23 09:33 UTC by m1ghtym0

2021-03-23 09:46 UTC, thomasten commented
Merge into main instead? IMO we should use dev only for docu of unreleased features.

2021-03-25 16:07 UTC, katexochen requested changes
Nice Quickstart! feels very welcoming :smile_cat:

2021-03-25 16:07 UTC, katexochen commented on content/docs/getting-started/quickstart.md
> +The simulation flag tells Marblerun that real SGX hardware might not be present and the SGX-layer should be emulated.
Maybe we should already mention in the intro that our demo does not use SGX and include a warning that this is not for production ;)

2021-03-25 16:07 UTC, katexochen commented on content/docs/getting-started/quickstart.md
> +kubectl -n marblerun logs -f -ledgeless.systems/control-plane-component=coordinator
```suggestion
kubectl -n marblerun logs -f -edgeless.systems/control-plane-component=coordinator
```
Not sure if this is a typo....

2021-03-25 16:22 UTC, m1ghtym0 commented on content/docs/getting-started/quickstart.md
> +kubectl -n marblerun logs -f -ledgeless.systems/control-plane-component=coordinator
No, that's actually correct. `-l` means filtering by label

2021-03-25 16:29 UTC, m1ghtym0 commented
I used the "we" form intentionally to have an "engaging" touch in the quickstart.
In the sense of "we're in this together, let's work through it".
Do you think that makes it sound less professional?

2021-03-27 09:46 UTC, katexochen commented
I think it is nice to use "we" in a context of "we are going to this step by step together". However, in my opinion it should only be used if this is indeed the case. If the user needs to install prerequisites before and without our help, it should state "you have to install ... first". The cluster used in a tutorial is the users cluster, not ours. It is nice to use "we" on a higher level view like "the next steps we are going to face are...", but atomar instuctions should still be in imparative, "run command foo ", "install bar with ...".

2021-03-29 13:47 UTC, katexochen approved these changes

2021-03-29 14:53 UTC, merged