AB#695: Documentation for graphene-prepare
edgelesssys/marblerun.sh pull request #31
Opened 2021-04-13 13:57 UTC by Nirusu

This PR:

- updates the available commands with the ones currently available 
- sorts the commands alphabetically 
- adds documentation for `graphene-prepare`

It's quite a bit more text for `graphene-prepare` than for some other commands. However, I think it is needed in a way because it is someway half between "magic" but also "only works under certain circumstances".

2021-04-14 07:51 UTC, m1ghtym0 requested changes

2021-04-14 07:51 UTC, m1ghtym0 commented on content/docs/getting-started/cli.md
> +These flags apply to all sub commands of certificate
```suggestion
These flags apply to all `certificate` subcommands
```

2021-04-14 07:51 UTC, m1ghtym0 commented on content/docs/getting-started/cli.md
> +Please note that this only works on a best-effort basis and may not instantly work correctly. While suggestions should be made for every valid TOML Graphene configuration, changes can only performed
```suggestion
This command helps you if you want to add Graphene-based services to your Marblerun service mesh.
It prepares your Graphene project to be used as a Marble.
Given your [Graphene manifest template](https://graphene.readthedocs.io/en/latest/manifest-syntax.html), it will suggest the required adjustments needed and adds our bootstrapping data-plane code to your Graphene image.
See [Building a service: Graphene]({{< ref "docs/tasks/build-service-graphene.md" >}}) for detailed information on Marblerun’s Graphene integration and our changes in your Graphene manifest.

Please note that this only works on a best-effort basis and may not instantly work correctly.
While suggestions should be made for every valid TOML Graphene configuration, changes can only be performed for non-hierarchically sorted configurations. as the official Graphene examples.
The unmodified manifest is saved as a backup under the old path with an added ".bak" suffix, allowing you to try out and roll back any changes performed.

Remember, you need to create a [Marblerun manifest]({{< ref "docs/tasks/define-manifest.md" >}}) in addition to the Graphene manifest. Adding Graphene packages to your manifest is straightforward and follows the same principles as any other SGX enclave.
```

2021-04-14 07:51 UTC, m1ghtym0 commented on content/docs/getting-started/cli.md
> +  Adds the premain as a shared library loaded on launch of your application via LD_PRELOAD. Allows for a faster launch than `spawn` and delegates more features to Graphene (but restricts Marblerun's
```suggestion
  Adds the premain as a shared library loaded during the launch of your application via LD_PRELOAD. Allows for a faster launch than `spawn` and delegates more features to Graphene (but restricts Marblerun's functionalities), making it the quickest way to adapt your existing application. However, features such as argv provisioning cannot be used in Marblerun anymore in this mode.
```

2021-04-14 07:51 UTC, m1ghtym0 commented on content/docs/getting-started/cli.md
> +  Replaces the original entrypoint of your application with the premain process which eventually spawns your application. Dedicates argv provisioning to Marblerun, so make sure your Marblerun manifes
```suggestion
  Replaces the original entrypoint of your application with the bootstrapping Marble premain process which eventually spawns your application. Dedicates argv provisioning to Marblerun. If you configured the arguments to your Graphene application through the [Graphene manifest](https://graphene.readthedocs.io/en/latest/manifest-syntax.html#command-line-arguments) before, you need to transfer those to the [Marblerun manifest]({{< ref "docs/tasks/define-manifest.md#manifestmarbles">}}).
```

2021-04-14 14:22 UTC, Nirusu commented
Applied suggestions & rebase to current dev with latest additions by @daniel-weisse. Hope we can merge this with #35 for 0.3.1 release.

2021-04-14 14:30 UTC, daniel-weisse commented on content/docs/getting-started/cli.md
>    manifest    Manages manifest for the Marblerun coordinator
The spacing in this part is off
```suggestion
  certificate      Retrieves the certificate of the Marblerun coordinator
  check            Check the status of Marbleruns control plane
  graphene-prepare Modifies a Graphene manifest for use with Marblerun
  help             Help about any command
  install          Installs marblerun on a kubernetes cluster
  manifest         Manages manifest for the Marblerun coordinator
```

2021-04-14 14:36 UTC, Nirusu commented on content/docs/getting-started/cli.md
>    manifest    Manages manifest for the Marblerun coordinator
You're right. Fixed, thanks!

2021-04-15 15:05 UTC, m1ghtym0 approved these changes

2021-04-15 15:05 UTC, m1ghtym0 commented on content/docs/getting-started/cli.md
> +  CLI Version: v0.3.0
Ich denke es macht nicht so wirklich Sinn hier immer die Version Strings mit jedem release zu ändern, oder seht ihr das anders?

2021-04-15 15:09 UTC, daniel-weisse commented on content/docs/getting-started/cli.md
> +  CLI Version: v0.3.0
"The output is similar to the following:"
Der commit hash ändert sich ja auch mit jeder version, ist ja nur als Beispiel wie es aussehen könnte

2021-04-15 16:32 UTC, Nirusu commented on content/docs/getting-started/cli.md
> +  CLI Version: v0.3.0
Würde einfach 0.3.0 da stehen lassen, ist ja nur ein Example. Außer natürlich, wir ändern die Ausgabe irgendwann.

2021-04-16 08:46 UTC, merged