AB#750 libOS: Add Occlum support & Graphene changes
edgelesssys/marblerun.sh pull request #40
Opened 2021-05-03 14:06 UTC by Nirusu

- Removes `preload` method for Graphene (which became obsolete by https://github.com/edgelesssys/marblerun/pull/153)
- Adds documentation for how to use Marblerun with Occlum (https://github.com/edgelesssys/marblerun/pull/146)

Please review & leave suggestions regarding to the wording, would be appreciated :)

2021-05-04 06:02 UTC, m1ghtym0 requested changes

2021-05-04 06:02 UTC, m1ghtym0 commented on content/docs/building-services/occlum.md
> +panic: posix_spawn failed with error code -1
Is this still the error message?

2021-05-04 06:02 UTC, m1ghtym0 commented on content/docs/examples/occlum.md
> +Checkout the provided manifests and the Makefile to get an understanding of how an Occlum application can be integrated within Marblerun.
```suggestion
To get you started to port your Occlum application for use with Marblerun, we offer you an example with an [a "Hello World" application](https://github.com/edgelesssys/marblerun/tree/master/samples/occlum-hello).
Checkout the provided manifests and the Makefile to get an understanding of how an Occlum application can be integrated within Marblerun.
```

2021-05-04 09:14 UTC, Nirusu commented on content/docs/building-services/occlum.md
> +panic: posix_spawn failed with error code -1
[It is.](https://github.com/edgelesssys/marblerun/blob/master/cmd/premain-occlum/main.go#L52)

2021-05-04 09:16 UTC, Nirusu commented on content/docs/building-services/occlum.md
> +In case you are running into issues with memory demands, check out the [Resource Configuration guide](https://github.com/occlum/occlum/blob/master/docs/resource_config_guide.md) provided by the Occlu
Don't know about that one. It's the title of the document, following the capitalized headline rules common for English. Personally, I like it capitalized as it highlights that it points to a guide (highlights it is the title of the guide).

Though then, I should have capitalized guide, too...

2021-05-04 09:22 UTC, m1ghtym0 commented on content/docs/building-services/occlum.md
> +In case you are running into issues with memory demands, check out the [Resource Configuration guide](https://github.com/occlum/occlum/blob/master/docs/resource_config_guide.md) provided by the Occlu
Yep, either way works for me, but should be consistent.

2021-05-04 09:34 UTC, thomasten commented on content/docs/building-services/occlum.md
> +In case you are running into issues with memory demands, check out the [Resource Configuration guide](https://github.com/occlum/occlum/blob/master/docs/resource_config_guide.md) provided by the Occlu
pls adhere to our styl guide https://github.com/edgelesssys/wiki/blob/master/documentation/writing_documentations.md#language

2021-05-04 11:05 UTC, Nirusu commented on content/docs/building-services/occlum.md
> +In case you are running into issues with memory demands, check out the [Resource Configuration guide](https://github.com/occlum/occlum/blob/master/docs/resource_config_guide.md) provided by the Occlu
[Microsoft style guidelines say the following](https://docs.microsoft.com/en-us/style-guide/capitalization#title-style-capitalization):

> Occasionally, title-style capitalization—capitalizing most words—is appropriate. For example, product and service names, the names of blogs, book and song titles, article titles in citations, white paper titles, and titles of people (Vice President or Director of Marketing) require title-style capitalization. In a tweet, it's OK to use title-style capitalization to highlight the name of a quoted article.

Wouldn't that count as a title/name of a quoted article?

2021-05-04 12:37 UTC, m1ghtym0 approved these changes

2021-05-05 06:53 UTC, katexochen approved these changes

2021-05-10 12:31 UTC, merged