AB#703 elaborate description of remote attestation
edgelesssys/marblerun.sh pull request #48
Opened 2021-05-30 14:20 UTC by katexochen

2021-05-31 12:26 UTC, m1ghtym0 requested changes
Thanks Paul!
I like those graphics. We should make sure we use one consistent design principle for graphics through the docs.
I'm not really design-savvy and would like to hear @flxflx opinion on the design?
Either way, we should document how we create those designs in our wiki for future reference.

2021-05-31 12:26 UTC, m1ghtym0 commented on content/docs/features/attestation.md
> +Hardware-rooted *remote attestation* is a key ingredient for distributed confidential apps. Marblerun relies heavily on the [*Data Center Attestation Primitives* (DCAP)](https://download.01.org/intel
Why cutting the introduction, too wordy?

2021-05-31 12:26 UTC, m1ghtym0 commented on content/docs/features/attestation.md
> +It generates a remote attestation quote which contains the hash of the root certificate as well as a hardware measurement of the enclave the Coordinator is running in.
```suggestion
Initially, the Marblerun Coordinator is deployed to the cluster.
The Coordinator generates an X.509 certificate chain with a root and intermediate certificate authority (CA).
It generates a remote attestation quote which contains the hash of the root certificate as well as a hardware measurement of its enclave.
```

2021-05-31 12:26 UTC, m1ghtym0 commented on content/docs/features/attestation.md
> +This ensures that the certificate was indeed generated by the Coordinator and wasn't manipulated during transport.
```suggestion
The admin receives the quote and verifies the Coordinator's integrity via the measurement. Next, they verify that the quote contains the root certificate’s hash. This ensures that the certificate was indeed generated by this Coordinator and was not manipulated during transport.
```

2021-05-31 12:26 UTC, m1ghtym0 commented on content/docs/features/attestation.md
> +The manifest describes which Marbles (services) should be deployed to your cluster. It contains a measurement values of the Marbles which were made after the Marbles were built.
```suggestion
The manifest describes which Marbles (services) should be deployed to your cluster. It contains their enclaves’ build-time measurements. The manifest is described in more detail in our [“defining a manifest”] ]({{< ref " docs/workflows/define-manifest.md">}}) section. 
```

2021-05-31 12:26 UTC, m1ghtym0 commented on content/docs/features/attestation.md
> +The Coordinator's certificate Chain was well as the freshly generated Marble certificate are then delivered to the Marble.
```suggestion
This concludes the Coordinator’s initialization. From then on it enforces the manifest and only admits the desired Marble(s) to the cluster.
Each Marble registers itself with a quote via gRPC to the Coordinator.
The quote contains this Marble's measurements. The Coordinator compares them to the manifest to ensure the Marble's identity and integrity.
The [Marble's TLS credentials]({{< ref "docs/features/secrets-management.md" >}}) are generated by the Coordinator and signed with the intermediate CA certificate.
The Coordinator's certificate chain as well as the freshly generated Marble certificate are then delivered to the Marble.
```

2021-05-31 12:26 UTC, m1ghtym0 commented on content/docs/features/attestation.md
> +Different Marbles can communicate with each other in the same way.
```suggestion
The Marble and the Coordinator can now communicate securely and authenticated over TLS (with client authentication), using the Coordinator's CA as a root of trust.
Different Marbles can communicate with each other in the same way.
```

2021-05-31 12:26 UTC, m1ghtym0 commented on content/docs/features/attestation.md
> +If a client (i.e. a relying party, a customer) wants to connect to a Marble, the Coordinators certificate is used to establish a TLS connection and verify the Marble's certificate.
```suggestion
If a client (i.e., a relying party, a customer) wants to connect to a Marble, the Coordinator’s certificate is used as a trusted CA to establish a TLS connection and verify the Marble's certificate.
```

2021-05-31 12:26 UTC, m1ghtym0 commented on content/docs/features/attestation.md
> +The quote also contains a measurement of the Coordinator, which is verified against the measurement received by the admin or operator.
```suggestion
The Coordinator issues one concise remote-attestation statement for your whole distributed app.
The Coordinator's build-time measurement is distributed to the relying party (this must be done by the admin or operator).
The relying party requests the Coordinator's quote and certificate chain.
The quote contains the hash of the Coordinator's root CA certificate, which is verified against the received certificate chain.
The quote also contains the Coordinator's measurement, which is verified against the build-time measurement.
```

2021-05-31 12:26 UTC, m1ghtym0 commented on content/docs/features/attestation.md
> +The steps required on the client-side are described in our [verification hands-on]({{< ref "docs/workflows/verification.md" >}}).
```suggestion
The relying party then requests the manifest from the Coordinator and ensures it contains the expected Marbles and their expected measurements.
The steps required on the client-side are described in our [verification hands-on]({{< ref "docs/workflows/verification.md" >}}).
```

2021-06-02 05:57 UTC, katexochen commented on content/docs/features/attestation.md
> +Hardware-rooted *remote attestation* is a key ingredient for distributed confidential apps. Marblerun relies heavily on the [*Data Center Attestation Primitives* (DCAP)](https://download.01.org/intel
yes, I wanted to cap the total length of the article.

2021-06-02 06:02 UTC, katexochen commented on content/docs/features/attestation.md
> +This ensures that the certificate was indeed generated by the Coordinator and wasn't manipulated during transport.
Less linebreaks in the code?

2021-06-02 07:41 UTC, m1ghtym0 commented on content/docs/features/attestation.md
> +This ensures that the certificate was indeed generated by the Coordinator and wasn't manipulated during transport.
Removing the linebreaks was unintentional, but I tried to shorten this section a bit.

2021-06-08 15:41 UTC, flxflx approved these changes
Graphics look great - thank you!

2021-06-09 06:33 UTC, m1ghtym0 approved these changes

2021-06-09 06:37 UTC, merged