draft ttls in marblerun
edgelesssys/marblerun.sh pull request #49
Opened 2021-05-31 14:59 UTC by 3u13r

The first draft to describe the TTLS feature. I tried to be as precise and short as possible. 
I saw that the other feature descriptions also explained the general use-case inside marblerun. This part probably needs to be more flashed out. 

I welcome all suggestions and corrections. Concrete questions are included below.

2021-05-31 15:07 UTC, 3u13r commented on content/docs/features/transparent-TLS.md
> +To achieve security and verifiability, services need to communicate via TLS. To simplify migrating existing applications to Marblerun, Transparent TLS (TTLS) can wrap any defined connections in TLS.
How much should we add here about why we use TLS in the first place. If I understand correctly this is mostly covered by features/secret-management and features/attestation. Should we move some parts here, reiterate the important parts (which?), or just reference it?

2021-05-31 15:15 UTC, 3u13r commented on content/docs/workflows/define-manifest.md
> +The TLS entry holds a list of tags which can be used in a marble's definition. Each tag can define multiple `Incoming` and `Outgoing` connections. Outgoing connections are defined by `Port` and `Addr
Should we warn about the disabling of client authentication in a highlighted box?

2021-06-01 09:12 UTC, m1ghtym0 commented on content/docs/workflows/define-manifest.md
> +                "front", "other"
Why don't we name them similar to the service?

2021-06-01 09:12 UTC, m1ghtym0 commented on content/docs/workflows/define-manifest.md
> +The TLS entry holds a list of tags which can be used in a Marble's definition. Each tag can define multiple `Incoming` and `Outgoing` connections. Outgoing connections are defined by `Port` and `Addr
Why do previously defined certificates disable client authentication?
Wouldn't it be better to have an explicit parameter for that?
`domains` are a bit ambiguous and probably require one more sentence on DNS names.

2021-06-02 06:33 UTC, 3u13r commented on content/docs/workflows/define-manifest.md
> +                "front", "other"
If I understand correctly service meaning marble?
I wanted to emphasize that the names of the tags are arbitrary and don't need to exactly match the services.

2021-06-02 06:33 UTC, 3u13r commented on content/docs/workflows/define-manifest.md
> +The TLS entry holds a list of tags which can be used in a Marble's definition. Each tag can define multiple `Incoming` and `Outgoing` connections. Outgoing connections are defined by `Port` and `Addr
Currently, client authentication is automatically disabled as specified in https://github.com/edgelesssys/emojivoto/pull/11#issuecomment-790501876. This would only need a small change in marblerun to be able to configure it manually. There are probably use cases where client authentication can/must be enabled. If there are no objections, I will add this feature. 

I'll also add some more information on the `domains` part, here. Especially that the internal kubernetes domains can be used.

2021-06-02 06:37 UTC, katexochen commented on content/docs/features/transparent-TLS.md
> +While user-defined TLS credentials can be used, Marblerun defaults to the [marble's credentials]({{< ref "docs/features/secrets-management.md" >}}). Since all Marble's certificates are signed by the
"RootCA" -> "root CA"

2021-06-02 10:03 UTC, daniel-weisse commented on content/docs/workflows/define-manifest.md
> +                "front", "other"
Maybe change the labels from `front` and `back` to `frontend_tls` and `backend_first_tls`?
This way we keep the naming from the service, but also show that the names don't need to match

2021-06-03 14:24 UTC, thomasten commented on content/docs/features/transparent-TLS.md
> +To achieve security and verifiability, services need to communicate via TLS. To simplify migrating existing applications to Marblerun, Transparent TLS (TTLS) can wrap any connection in TLS without an
After reading this, I wouldn't know why I'd need this feature. Should we start with a problem description?

2021-06-03 14:26 UTC, thomasten commented on content/docs/workflows/define-manifest.md
> +                "front", "other"
TLS tags/labels should be named after what they provide, not after the marble(s) that use them.

2021-06-03 14:40 UTC, thomasten commented on content/docs/features/transparent-TLS.md
> +While user-defined TLS credentials can be used, Marblerun defaults to the [marble's credentials]({{< ref "docs/features/secrets-management.md" >}}). Since all Marble's certificates are signed by the
Start with the default.
The internal credentials were a crutch and are now an implementation detail - scratch that. Just point out that they are automatically configured.
Explain why/when you would define your own credentials.

2021-06-03 14:52 UTC, thomasten commented on content/docs/workflows/define-manifest.md
> +                }
We should also show how to define an incoming connection for the most common case, i.e., internal mutual TLS.

2021-06-03 14:52 UTC, thomasten commented on content/docs/workflows/define-manifest.md
> +                }
I think this is a bad example in the CC context.

2021-06-03 14:52 UTC, thomasten commented on content/docs/workflows/define-manifest.md
> +The TLS entry holds a list of tags which can be used in a Marble's definition. Each tag can define multiple `Incoming` and `Outgoing` connections. Outgoing connections are defined by `Port` and `Addr
> Incoming connections just use `Port` and always define `Addr` as `"*"`.

So why do they define `Addr` at all?

2021-06-03 14:52 UTC, thomasten commented on content/docs/workflows/define-manifest.md
> +The TLS entry holds a list of tags which can be used in a Marble's definition. Each tag can define multiple `Incoming` and `Outgoing` connections. Outgoing connections are defined by `Port` and `Addr
This paragraph should be split in two or three
* Short intro and common facts (if any)
* Incoming connections: Why, when, and how to use them (internal mutual vs external)
* Outgoing connections: Why, when, and how to use them

2021-06-04 14:05 UTC, 3u13r commented on content/docs/workflows/define-manifest.md
> +                "front", "other"
I'm kind of agree and disagree. IMO, the most probable scenario is something like 5 gRPC Services and maybe 1 web service. Now we maybe want to share the configuration of the gRPC services.  Even if they all listen on the same port, and the Incoming definition can be shared, we would still need to define each service in the Outgoing section. Therefore, we also define that Service1 connection to Service1 should be wrapped, which makes little sense. I see that it is nice to have all the services that talk to each other in one list (e.g. the Outgoing part), but this overdefinition can quickly explode, e.g. when Service1 only talks to Service2 and Service2 only to Service3. Seeing those services grouped as one TLS definition makes me think that Service1 talks to every service in the list.  Again, assuming they all use the same incoming port. Therefore, my way of configuring would be marble-wise, if there is no good reason not to. Maybe I would even define an "gRPC_incoming" tag, use that for each marble and define the Outgoing part separately for each.  

Furthermore, it is quite hard to show the different variations with 2 of them. 

tl;dr: 2 Options: By default TLS labels define 
1. marbles (1-to-1)  
2. "groups" of marbles (1-to-n)

2021-06-04 14:18 UTC, 3u13r commented on content/docs/workflows/define-manifest.md
> +The TLS entry holds a list of tags which can be used in a Marble's definition. Each tag can define multiple `Incoming` and `Outgoing` connections. Outgoing connections are defined by `Port` and `Addr
We could leave it out and define it in marblerun ourselves. We also could leave it there to remind the user that we don't bind on a specific interface but all interfaces.

2021-06-04 14:31 UTC, thomasten commented on content/docs/workflows/define-manifest.md
> +                "front", "other"
I don't get all of what you say, but doesn't matter.

> we would still need to define each service in the Outgoing section

You can have an Outgoing rule with a wildcard address and fixed port. One could argue that a wildcard address is always preferable regarding security. At least it's not dangerous.

> Maybe I would even define an "gRPC_incoming" tag

Yes, that's my point.

In general, the feature is designed to support n-to-m. (One reason is avoiding duplicate entries in multiple TLS definititions.)

Anyway, I didn't necessarily want anything to be changed in this example, but just clarify to all participants that "name them similar to the service" is not the rule of thumb.

2021-06-04 14:47 UTC, thomasten commented on content/docs/workflows/define-manifest.md
> +The TLS entry holds a list of tags which can be used in a Marble's definition. Each tag can define multiple `Incoming` and `Outgoing` connections. Outgoing connections are defined by `Port` and `Addr
Sorry, I thought we already support leaving it out. So is the following valid or not?
https://github.com/edgelesssys/marblerun/blob/3891ebcbf717e51218c9c3bb3b66270f6dd9713b/test/manifests.go#L152-L155

2021-06-04 15:16 UTC, 3u13r commented on content/docs/workflows/define-manifest.md
> +The TLS entry holds a list of tags which can be used in a Marble's definition. Each tag can define multiple `Incoming` and `Outgoing` connections. Outgoing connections are defined by `Port` and `Addr
Sorry, I had to look into the marblerun implementation again. Currently, your example is already supported. I have no idea why I defined Addr as "*". So I will just remove the sentence and replace it with something like: "Incoming connections just use `Port` and which will be used on all interfaces."

2021-06-04 15:46 UTC, 3u13r commented
Just for visibility: Now added (in https://github.com/edgelesssys/marblerun.sh/pull/49/commits/9ec7577eb86ccf1b91bbb413344d63b11a49e8ef) the change requests by @thomasten as well as the `DisableClientAuth` flag.

2021-06-05 16:36 UTC, thomasten requested changes

2021-06-05 16:36 UTC, thomasten commented on content/docs/workflows/define-manifest.md
> +Incoming connections are listened to on all interfaces and are only defined by `Port`. For services that are used by external clients, you must set `Cert`. Previously defined certificates can be refe
```suggestion
Incoming connections are defined by `Port`. All interfaces will be intercepted.. For services that are used by external clients, you must set `Cert`. Previously defined certificates can be referenced here by name. Client authentication then needs to be disabled by setting `DisableClientAuth` to `true`.
```
"Incoming connections are listened to on all interfaces" reads odd. Maybe even wrong as it may suggest that TTLS controls on what interfaces to listen. However, my suggestion still is hard to understand without more context. Does it even add value to mention this at all? May be more confusing than helpful to most readers.

2021-06-05 16:36 UTC, thomasten commented on content/docs/workflows/define-manifest.md
> +Incoming connections are listened to on all interfaces and are only defined by `Port`. For services that are used by external clients, you must set `Cert`. Previously defined certificates can be refe
```suggestion
Incoming connections are listened to on all interfaces and are only defined by `Port`. For services used by external clients, you must disable client authentication by setting `DisableClientAuth` to `true` and set `Cert`. Use the name of a certificate defined in the [Secrets section](#manifestsecrets).
```
I tried to make the reason for disabling client auth more clear by (grammatically) binding it to "external clients".

2021-06-05 16:36 UTC, thomasten commented on content/docs/workflows/define-manifest.md
> +Outgoing connections are defined by `Port` and `Addr`. Both domains and IPs can be used as `Addr`. Most importantly, the DNS names of other services can be used.
```suggestion
Outgoing connections are defined by `Port` and `Addr`. For `Addr`, you can use both IP addresses and domains, e.g., the DNS names of other services.
```
prefer active voice where possible (if it doesn't complicate the sentence or sound odd)

2021-06-07 10:34 UTC, thomasten commented on content/docs/workflows/add-service.md
> +We recommend using [EGo]({{< ref "docs/building-services/ego.md" >}}) as runtime for all Go applictions, since there is no recompiling necessary when using [TTLS]({{< ref "docs/features/transparent-T
You still need to recompile with EGo. I think you can just revert this change.

2021-06-07 10:36 UTC, thomasten commented
Can one of the other reviewers (@katexochen @daniel-weisse @m1ghtym0) review this again pls?

2021-06-08 07:00 UTC, m1ghtym0 approved these changes
LGTM:-)

2021-06-08 13:57 UTC, thomasten approved these changes

2021-06-08 14:12 UTC, merged