AB#989 /secrets endpoint
edgelesssys/marblerun.sh pull request #57
Opened 2021-06-22 09:07 UTC by daniel-weisse

Adds the `/secrets` endpoint to the docs.

This includes updates to the CLI and a new workflows entry explaining the why and how of the endpoint.

2021-06-22 11:47 UTC, m1ghtym0 requested changes

2021-06-22 11:47 UTC, m1ghtym0 commented on content/docs/workflows/managing-secrets.md
> +Note that for this operation, you need to specify one of your defined `Users` certificates as a TLS client certificate, combined with the according private key.
```suggestion
Marblerun returns secrets over the client API in JSON format. 
Using the CLI, this output is formatted into an easily readable form, or directly saved to a file.
Note that for this operation, you need to provide the `Users` credentials you defined in the manifest.
```

2021-06-22 11:47 UTC, m1ghtym0 commented on content/docs/workflows/managing-secrets.md
> +The values one needs to set depend on the type of secret:
```suggestion
A user can upload secrets via the REST-API in JSON format. The secrets need to be marked as `UserDefined` in the manifest.
Each entry in the JSON dictionary is labeled by the name of the secret and contains values depending on its type:
```

2021-06-22 11:47 UTC, m1ghtym0 commented on content/docs/workflows/managing-secrets.md
> +This file can then be uploaded using the CLI, once again requiring a `Users` certificate and matching private key:
```suggestion
This file can then be uploaded using the CLI and the users credentials:
```

2021-06-22 11:47 UTC, m1ghtym0 commented on content/docs/workflows/define-manifest.md
> +The optional entry `Users` can be used to define one or multiple users.
```suggestion
The optional entry `Users` defines user credentials and permissions for authentication and access control.
```

2021-06-22 11:47 UTC, m1ghtym0 commented on content/docs/workflows/define-manifest.md
> +Each user requires one PEM-encoded self-signed X.509 certificates for authentication and allows the allocation of various permissions.
```suggestion
Each user is authenticated via a public key. The key needs to be specified as a PEM-encoded self-signed X.509 certificate.
```

2021-06-22 11:47 UTC, m1ghtym0 commented on content/docs/workflows/define-manifest.md
> +Marblerun requires the definition of at least one user for updating a manifest or setting user-defined secrets. The process of updating a manifest is described in our [updating a manifest hands-on]({
This sounds like you always have to specify at least one user. But this is only the case if updating the manifest should be possible later on, right?

2021-06-22 11:47 UTC, m1ghtym0 commented on content/docs/reference/cli.md
> +  Secrets are returned in JSON format with key data in base64 encoding.
```suggestion
  Retrieves one or more secrets from the coordinator. Requires credentials in the form of a private key and a self-signed certificate of the corresponding public key. The corresponding user needs to have access to the requested secrets. Secrets are returned in JSON format with base64 encoding.
```

2021-06-22 11:47 UTC, m1ghtym0 commented on content/docs/reference/cli.md
> +  Secrets are returned in JSON format with key data in base64 encoding.
Can't we generate public key and certificate in the CLI?

2021-06-22 11:47 UTC, m1ghtym0 commented on content/docs/reference/cli.md
> +  Secrets to set are specified in a special secrets file in json format. For more information see [Managing Secrets]({{< ref "docs/workflows/managing-secrets.md" >}}).
```suggestion
  Sets one or more secrets for the coordinator. Requires credentials in the form of a private key and a self-signed certificate of the corresponding public key. The corresponding user needs to have access to the requested secrets.
  Secrets to set are specified in JSON format. For more information see [Managing Secrets]({{< ref "docs/workflows/managing-secrets.md" >}}).
```

2021-06-22 11:47 UTC, m1ghtym0 commented on content/docs/reference/coordinator.md
> +Setting secrets requires uploading a file containing the secrets using a POST request. For more information refer to [Managing Secrets]({{< ref "docs/workflows/managing-secrets.md" >}}).
```suggestion
Setting secrets requires uploading them in JSON format using a POST request. For more information refer to [Managing Secrets]({{< ref "docs/workflows/managing-secrets.md" >}}).
```

2021-06-22 12:04 UTC, m1ghtym0 commented on content/docs/reference/cli.md
> +  Secrets are returned in JSON format with key data in base64 encoding.
Do we need a self-signed cert, or would a public key be sufficient?

2021-06-22 12:41 UTC, daniel-weisse commented on content/docs/reference/cli.md
> +  Secrets are returned in JSON format with key data in base64 encoding.
The certificate (and matching public key) is the one set in the manifest. We are using the same authentication method as used for manifest update.

2021-06-22 13:14 UTC, daniel-weisse commented on content/docs/workflows/define-manifest.md
> +Marblerun requires the definition of at least one user for updating a manifest or setting user-defined secrets. The process of updating a manifest is described in our [updating a manifest hands-on]({
Correct. Users are completely optional if the update or secret functionality is not needed.
Maybe remove the line completely? 
If we want an explicit warning for needing at least one user with update permission if updates need to be deployed, i think a better place would be either `update-manifest.md` or a mention in a section that explains the permission/roles feature

2021-06-23 11:05 UTC, m1ghtym0 commented on content/docs/reference/cli.md
> +  Secrets are returned in JSON format with key data in base64 encoding.
I see.
We might want to think about just using a key pair instead of the self-signed certificate for the sake of usability.
But that's a different discussion.

2021-06-23 13:41 UTC, m1ghtym0 approved these changes

2021-06-23 13:41 UTC, m1ghtym0 commented on content/docs/workflows/define-manifest.md
> +Users can perform [update a manifest]({{< ref "docs/workflows/update-manifest.md">}}) and [read or write secrets]({{< ref "docs/workflows/managing-secrets.md" >}}).
Sorry, after considering our current client authentication mechanism, we should actually use the term certificate here.
```suggestion
Each user is authenticated via a client certificate. The certificate needs to be specified as a PEM-encoded self-signed X.509 certificate.
Users can perform [update a manifest]({{< ref "docs/workflows/update-manifest.md">}}) and [read or write secrets]({{< ref "docs/workflows/managing-secrets.md" >}}).
```

2021-06-23 17:07 UTC, flxflx requested changes
Good stuff - thanks! Added some notes that try to address readability.

2021-06-23 17:07 UTC, flxflx commented on content/docs/workflows/managing-secrets.md
> +A user can upload secrets via the REST-API in JSON format. The secrets need to be marked as `UserDefined`.
"Users can set secrets that are marked as `UserDefined` by uploading a JSON file. In the file, secrets can be defined as follows."

Does one say "JSON dictionary"?

2021-06-23 17:07 UTC, flxflx commented on content/docs/workflows/managing-secrets.md
> +The secrets will then be available to Marbles or other users over the REST-API. If the user lacks permission to set one of the secrets, or a secret the user tried to upload was malformed an error occ
"Subsequently, the secrets can be accessed by marbles and authorized users". 

I believe we don't need to reiterate that this works via the REST-API.

2021-06-23 17:07 UTC, flxflx commented on content/docs/workflows/managing-secrets.md
> +Alternatively the CLI also supports directly uploading a PEM encoded certificate and key.
I believe that it would be helpful to describe this simpler approach first.

2021-06-29 15:17 UTC, flxflx approved these changes

2021-06-29 15:17 UTC, merged