Secrets documentation
edgelesssys/marblerun.sh pull request #6
Opened 2020-12-07 15:42 UTC by Nirusu

Documentation for edgelesssys/marblerun#73 and edgelesssys/marblerun#76

Can be reviewed together with edgelesssys/marblerun#76

2020-12-07 16:47 UTC, m1ghtym0 requested changes

2020-12-07 16:47 UTC, m1ghtym0 commented on content/docs/features/secrets-management.md
> +This means that support for certificate pinning is not available so far. In case you need to pin a certificate, you should consider to set the secret to be shared across all marbles (which get stored
```suggestion
The Coordinator will generate a private TLS key for each new Marble and issue a corresponding X.509 certificate. Both are injected via the `{{ pem .Marblerun.MarbleCert.Private }}` and `{{ pem .Marblerun.MarbleCert.Cert }}` placeholders in the Manifest, respectively. The certificate is signed by the Coordinator's RootCA. Marbles can use these TLS credentials for establishing trust and secure communication channels internally between other Marbles and externally between clients. A Marble's certificate can be verified with respect to the Coordinator's RootCA certificate. The RootCA certificate can be injected into Marbles via the  `{{ pem .Marblerun.RootCA.Cert }}` placeholder. External clients can retrieve it in the remote attestation process described [here](({{< ref "docs/tasks/verification.md" >}})) in detail.

## User-definable secrets
Next to the predefined secrets, Marblerun also allows specifying additional secrets that can be generated on-the-fly and be either confined to a single marble or shared across all of them. These can be either symmetric keys or certificates, which can be referenced via the `{{ .Secret }}` prefix and loaded into environment variables or a file, similar to the predefined keys and their placeholders. Name, size, and duration of validity (for certificates) are user-definable, and supported output formats are `raw`, `hex`, `base64`, or `pem`.

Keys and certificates which are set to be unique to a Marble are not persisted on the disk automatically. They are generated by the Coordinator when a Marble is activated. For symmetric keys, the [HKDF](https://tools.ietf.org/html/rfc5869) scheme is used with an embedded secret to deterministically derive the same key across multiple activations of the same marble. Fresh X.509 certificates are generated on every activation with the Coordinator's root CA certificate as the issuer. 

This means that support for certificate pinning is not available so far. In case you need to pin a certificate, you should consider setting the secret to be shared across all marbles or to generate a fixed one in your application logic itself.
```

2020-12-07 16:47 UTC, m1ghtym0 commented on content/docs/tasks/define-manifest.md
> +* `Cert` (only for certificates): Allows the user to specify parameters for the x509 certificate which should be generated. This maps directly to a Go x509.Certificate object, and every supported val
```suggestion
The following parameters are available:
* `Type`: Can be either `raw` (symmetric key), `cert-rsa`, `cert-ecdsa` or `cert-ed25519`
* `Size`: Defines the size of the key used to generate the secret. As common for symmetric keys, for a secret of type `raw`, the size needs to be divisible by 8. For an ECDSA certificate, the size needs to map to a valid curve supported by Go's crypto library, which are currently (P-)224, 256, 384, or 521. For an ed25519 certificate, the parameter `size` needs to be omitted as in this case, the elliptic key used is always of the size 256.
* `Shared` (default: `false`): Specifies if the secret should be shared across all Marbles and sealed into the Coordinator's state (`true`), or if the secret should be uniquely generated for each Marble (`false`). Keep in mind that secrets confined to a Marble come with certain limitations by now. For more information, look up the section [Secrets management]({{< ref "docs/features/secrets-management.md" >}}).
* `ValidFor` (only for certificates, default: `365`): Defines how long the certificate should be valid after generation in days. If not specified, a default value of `365` (365 days) is used. Please note that this field cannot be specified in combination with the `NotAfter` field in `Cert`. Only one of them can be defined.
* `Cert` (only for certificates): Allows the user to specify parameters for the x509 certificate which should be generated. This maps directly to a Go x509.Certificate object and every supported value can be specified, though certain ones (listed below) will either be filled automatically if left empty or even get replaced.
```

2020-12-08 13:18 UTC, m1ghtym0 approved these changes

2020-12-08 13:19 UTC, thomasten requested changes

2020-12-08 13:19 UTC, thomasten commented on content/docs/features/secrets-management.md
> +This means that support for certificate pinning is not available so far. In case you need to pin a certificate, you should consider setting the secret to be shared across all marbles or to generate a
I'm not sure whether we should have these implementation details in the documentation for the end user. Maybe just mention the consequences? Or leave it out completely and add the feature if someone complains about it?

2020-12-08 13:19 UTC, thomasten commented on content/docs/tasks/define-manifest.md
> +* `Shared` (default: `false`): Specifies if the secret should be shared across all Marbles and sealed into the Coordinator's state (`true`), or if the secret should be uniquely generated for each Mar
```suggestion
* `Shared` (default: `false`): Specifies if the secret should be shared across all Marbles (`true`), or if the secret should be uniquely generated for each Marble (`false`). Keep in mind that secrets confined to a Marble come with certain limitations by now. For more information, look up the section [Secrets management]({{< ref "docs/features/secrets-management.md" >}}).
```

2020-12-08 13:19 UTC, thomasten commented on content/docs/tasks/define-manifest.md
> +        "IsCA": false,
```suggestion
        "SignatureAlgorithm": 0,
        "SerialNumber": null,
        "Subject": {
            "Country": null,
            "Organization": null,
            "OrganizationalUnit": null,
            "Locality": null,
            "Province": null,
            "StreetAddress": null,
            "PostalCode": null,
            "SerialNumber": "",
            "CommonName": "",
            "Names": null,
            "ExtraNames": null
        },
        "NotAfter": "0001-01-01T00:00:00Z",
        "KeyUsage": 0,
        "ExtKeyUsage": null,
        "UnknownExtKeyUsage": null,
```
Let's limit this to fields that can actually be set.

2020-12-08 13:52 UTC, Nirusu commented on content/docs/features/secrets-management.md
> +This means that support for certificate pinning is not available so far. In case you need to pin a certificate, you should consider setting the secret to be shared across all marbles or to generate a
I think stuff like the output formats, what exactly is definable etc. can be removed as it is mentioned in the manifest definition. 

About the implementation details... I'm not quite sure, the other sections are also pretty technical and mention certain points and security implications. I think it's important to mention that these generated certificates cannot be used for certificate pinning. After all, an user searching for a solution for confidential computing would care about features which ensure confidentiality, right? So leaving it undocumented does not seem like a great idea to me, but maybe we can move it somewhere else if it looks out of place here.

2020-12-13 18:01 UTC, flxflx commented
Should we add a note to the changelog?

2020-12-14 07:54 UTC, Nirusu commented
Yup, think that would make sense as it also changes the existing placeholders.

2020-12-17 08:29 UTC, merged