AB#1059 Add roles / permissions
edgelesssys/marblerun.sh pull request #60
Opened 2021-07-01 14:07 UTC by daniel-weisse

Explains user permissions, or more specifically, roles in the docs.
PR for the implementation in Marblerun: https://github.com/edgelesssys/marblerun/pull/189

2021-07-01 16:08 UTC, m1ghtym0 requested changes

2021-07-01 16:08 UTC, m1ghtym0 commented on content/docs/workflows/define-manifest.md
> +Valid `Actions` are:
```suggestion
Marblerun supports Role-based access control (RBAC).
An RBAC Role contains rules that represent a set of permissions for the Marblerun entities `Users` and `Marbles`. Permissions are purely additive (there are no "deny" rules).
Each role defines a `ResourceType` (one of `Packages` or `Secrets`), a list of `ResourceNames` of that type, and a list of `Actions` that role permits on the listed resources. \
Valid `Actions` are:
```

2021-07-01 16:08 UTC, m1ghtym0 commented on content/docs/workflows/define-manifest.md
> +Manifest updates will only be possible if you created a role allowing updates to the neccessary packages, and provided at least one user with said role.
```suggestion
Deployment updates will only be possible if you create a role with permissions to update the particular packages and bind a user to that role.
```

2021-07-01 16:08 UTC, m1ghtym0 commented on content/docs/workflows/update-manifest.md
> +Furthermore the user needs to be [permitted to update]({{< ref "docs/workflows/define-Manifest.md#manifestroles" >}}) the chosen packages.
```suggestion
In order to deploy an Update Manifest, you need to be in possession of a certificate/private key pair belonging to a user from the `Users` section of the original Manifest, as described in ["Defining a Manifest"]({{< ref "docs/workflows/define-Manifest.md#manifestmarbles" >}}).
Furthermore the user needs to be [permitted to update]({{< ref "docs/workflows/define-Manifest.md#manifestroles" >}}) the chosen packages.
```

2021-07-01 16:08 UTC, m1ghtym0 commented on content/docs/workflows/define-manifest.md
> +The optional entry `Users` defines user credentials and role-bindings for authentication and access control.
```suggestion
The optional entry `Users` defines user credentials and role bindings for authentication and access control.
```

2021-07-02 13:47 UTC, m1ghtym0 commented
Do we have role support for Marbles as well or only Users so far?

2021-07-02 13:49 UTC, daniel-weisse commented
Currently its only for Users

2021-07-02 14:02 UTC, merged