Add, fix & adjust a bunch of links
edgelesssys/marblerun.sh pull request #73
Opened 2021-07-22 12:56 UTC by Nirusu

I started adjusted the links mentioned in: https://github.com/edgelesssys/marblerun/issues/213

This is not complete yet, feel free to add the other points I have not ticked off yet. Maybe the other folks can also just add some commits here and we review this later on...?

Just one thing regarding the link to the containers: For Marblerun, I added a direct link to the Coordinator. For ego, we have two packages: dev and deploy, so I left the link. But personally, I didn't think that it was too confusing in the first place, at least if you are somewhat used to the package listing here on GitHub. Maybe someone has better ideas on how to handle this, or we just rewrite the section a bit...

2021-07-26 13:39 UTC, leongross requested changes

2021-07-26 13:39 UTC, leongross commented on content/docs/features/secrets-management.md
> +The generation and the management of cryptographic keys and certificates for Marbles (i.e., containers running enclaves) are central duties of the Coordinator. Keys and certificates are passed to Mar
```suggestion
The generation and the management of cryptographic keys and certificates for Marbles (i.e., containers running enclaves) are central duties of the Coordinator. Keys and certificates are passed to Marbles on startup via placeholders defined in the manifest. You can learn more about this mechanism in the `Secrets` section from our [manifest definition hands-on]({{< ref "docs/workflows/define-manifest.md#manifestsecrets" >}}). Specifically, the Coordinator provides the following to Marbles.
```

2021-07-26 14:01 UTC, daniel-weisse requested changes

2021-07-27 07:14 UTC, daniel-weisse approved these changes

2021-07-27 11:10 UTC, leongross approved these changes
lgtm

2021-07-27 11:11 UTC, merged